name: Build image and push to GHCR

on: 
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: get the code
        uses: actions/checkout@v6

      - name: Buildah
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: wondercms
          tags: ${{ github.event.inputs.version }}
          containerfiles: |
            ./Containerfile

      - name: Push to GHCR
        id: push
        uses: redhat-actions/push-to-registry@v2
        with:
          image: wondercms
          tags: ${{ github.event.inputs.version }}
          registry: ghcr.io/unixxsh
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}